### ISSUE TITLE
[Front API] OAuth 회원 조회 변경

### ISSUE THREAD

**Issue by osj3474** [brave-people/Dev-Event-Server#193]
OAuth에서 사용자 Email을 받아왔으면 Email을 user_id와 email 동시에 저장하고, 
user_id + AuthType으로 유효한 사용자를 식별해야하도록 변경
(user_id를 UUID 난수로 생성하고, email을 저장하지 않는 것)

**Comment by KoEonYack** [comment]
@osj3474 

이거 이슈내용 이전 정책인것같은데~ 

개발 History 기록을 위해서 최신화해서 작성해두고 issue closed 하면 될듯!
