### ISSUE TITLE
개발자 행사 다시보기 api spec 문의

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Server#194]
반가워요~~~ 도림천은 무사한가요..??! 😢
오늘도 비가 많이오네요~~~~,,

다시보기 만드는 중인데 궁금한게 있어 이슈로 남겨요

```json
"links": [
  {
    "link": "string",
    "link_type": "string (ex. HOMEPAGE)"
  }
],
``` 

swagger 모델은 이런데, 기획은 하나만 받을 수 있게 되어있어서 어느게 맞는것인지.. 문의하러왔어요~~~
link_type도 있는데 정해진 타입이 있을까요?
![스크린샷 2022-08-10 오후 9 51 45](https://user-images.githubusercontent.com/39582981/183905945-e90cffd9-b432-46d4-94ba-a414f8ad9087.png)

**Comment by KoEonYack** [comment]
@leedoopal 

반가워요~~~~~~

![스크린샷 2022-08-20 오후 3 11 32](https://user-images.githubusercontent.com/28642484/185731661-3d885021-e0e6-49e1-8879-42aeb1051b47.png)

기획서를 업뎃했어요!

https://github.com/brave-people/Dev-Event/blob/master/replay_event/replay_event.md

개발자 행사 다시보기 .md 파일을 보면 다시보기 링크가 홈페이지와 Youtube로 구분되어있어요!
