### ISSUE TITLE
[FE] 찜 리스트 API filter 개선제안  

### ISSUE THREAD

**Issue by ohh31** [brave-people/Dev-Event-Server#205]
안녕하세요! 주말 잘 보내시고 계신가요~??
웹 찜리스트 API에서 찜 리스트를 filter로 구분해 보내주시는데 filter를 제거하는 것을 제안드립니다!

제안 드리는 이유는 데브이벤트 웹에서 특정 이벤트가 찜 업데이트가 되지 않는 이슈가 있었는데요! (#35번, #34번)
프론트엔드에서 행사가 종료되는 조건과 서버에서 행사를 종료되는 조건이 달라서 발생한 문제였습니다! 
찜 추가를 할 때 프론트엔드에서 종료된 행사인지 조건을 확인 후 해당 조건에 맞는 filter로 api를 호출하고 있거든요

조건을 맞추는 것이 빠른 해결방안이겠지만 
프론트엔드에서 행사 종료를 관리하는 것이 앞으로의 커뮤니케이션을 줄이고 
프론트엔드 코드 관리 차원에서도 더 좋을 것 같다는 생각이 들어서 제안드립니다!

**Comment by KoEonYack** [comment]
@ohh31 

어제 이야기한대로 필터값을 보내지않으면 전체가 호출됨!

(filter값을 필수로 보내야한다는 Swagger는 수정예정)

@osj3474 

자주 보기는 힘들겠지만 상진이 답할 수 있는 issue가 있으면 답 주는것도 좋을듯~~!!
